/**
 * Bundles the official Anthropic SDK into one ES module the extension can
 * import without a build step:  npm run vendor  →  vendor/anthropic-sdk.js
 *
 * The output is committed so "Load unpacked" keeps working without npm.
 * Re-run after bumping @anthropic-ai/sdk in package.json.
 */
import { build } from "esbuild";
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const { version } = JSON.parse(await readFile(join(root, "node_modules/@anthropic-ai/sdk/package.json"), "utf8"));

await build({
  stdin: {
    contents: 'export * from "@anthropic-ai/sdk";\nexport { default } from "@anthropic-ai/sdk";\n',
    resolveDir: root,
    loader: "js"
  },
  bundle: true,
  format: "esm",
  platform: "browser",
  target: "chrome111",
  minify: true,
  legalComments: "eof",
  banner: { js: `// @anthropic-ai/sdk ${version}. Generated by scripts/build-vendor.mjs; do not edit.` },
  outfile: join(root, "vendor/anthropic-sdk.js"),
  logLevel: "info"
});
